# -*- coding: utf-8 -*-
"""351 final project data cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ufc50LFz8-j3xAgrQJ9rr4Y1GtKnlZen
"""

import pandas as pd

movies = pd.read_csv('/content/movies.csv')
netflix = pd.read_csv('/content/_netflix_titles.csv')
tv = pd.read_csv('/content/tv_shows.csv')

movies.info()
movies.isnull().sum()

netflix.info()
netflix.isnull().sum()

tv.info()
tv.isnull().sum()

for df in [movies, netflix, tv]:
  if 'duration' in df.columns:
    df.drop(columns='duration', inplace=True)

netflix['date_added'] = pd.to_datetime(netflix['date_added'], errors='coerce').dt.date

text_cols_movies = ['title', 'type']
text_cols_tv = ['title', 'type']
text_cols_netflix = ['title', 'type']

for col in text_cols_movies:
    if col in movies.columns:
        movies[col] = movies[col].str.lower()

for col in text_cols_tv:
    if col in tv.columns:
        tv[col] = tv[col].str.lower()

for col in text_cols_netflix:
    if col in netflix.columns:
        netflix[col] = netflix[col].str.lower()


combined = pd.concat([movies, tv, netflix], ignore_index=True)

joined = pd.merge(
    netflix,
    combined,
    how='outer',
    left_on=['title', 'release_year'],
    right_on=['title', 'release_year'],
    suffixes=('_netflix', '_collected')
)