# -*- coding: utf-8 -*-
"""data_cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ufc50LFz8-j3xAgrQJ9rr4Y1GtKnlZen
"""

import pandas as pd
import numpy as np


def run_data_cleaning(
    movies_path="movies.csv",
    tv_shows_path="tv_shows.csv",
    netflix_titles_path="netflix_titles.csv",
    output_path="cleaned_netflix_movies.csv"
):
    """
    Runs the full data cleaning and merging pipeline for the DSCI 351 Netflix project.

    Returns:
        final_df (pd.DataFrame): cleaned and merged dataset
    """

    # 1. Read CSV files
    movies = pd.read_csv(movies_path)
    tv_shows = pd.read_csv(tv_shows_path)
    netflix_titles = pd.read_csv(netflix_titles_path)

    dfs = [movies, tv_shows, netflix_titles]

    # 2. Missing values

    fill_values = {
        "description": "",
        "country": "Not Specified",
        "director": "Unknown",
        "cast": "Unknown",
    }

    for i, df in enumerate(dfs):
        # Drop duration column if present
        if "duration" in df.columns:
            df.drop(columns=["duration"], inplace=True)

        # Fill missing values
        df.fillna(fill_values, inplace=True)

        # Convert date_added to date
        if "date_added" in df.columns:
            df["date_added"] = pd.to_datetime(df["date_added"], errors="coerce")
            df["date_added"] = df["date_added"].dt.date

        # Standardize text columns
        for col in ["type", "title"]:
            if col in df.columns:
                df[col] = df[col].str.lower().str.strip()

        dfs[i] = df

    movies, tv_shows, netflix_titles = dfs

    # 3. Concatenate movies and tv_shows
    combined = pd.concat([movies, tv_shows], ignore_index=True)

    # 4. Merge with netflix_titles
    merged_df = pd.merge(
        combined,
        netflix_titles,
        on=["title", "release_year"],
        how="outer",
        suffixes=("_collected", "_netflix"),
    )

    # 5. duplicate columns
    cols_to_clean = [
        "type",
        "country",
        "description",
        "date_added",
        "director",
        "cast",
        "rating",
        "listed_in",
    ]

    for col in cols_to_clean:
        netflix_col = col + "_netflix"
        collected_col = col + "_collected"

        if netflix_col in merged_df.columns and collected_col in merged_df.columns:
            merged_df[col] = merged_df[netflix_col].combine_first(
                merged_df[collected_col]
            )
            merged_df.drop(columns=[netflix_col, collected_col], inplace=True)

    # 6. Drop duplicates

    final_df = merged_df.drop_duplicates(subset=["title", "release_year"])

    # 7. Save cleaned dataset
    final_df.to_csv(output_path, index=False)

    return final_df