# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VT0j4OcyCCB4tedCFGpDAeAPbNzjw2cr
"""

# DSCI 351 – Netflix Movie Review Analysis Pipeline
# Part 5: Main orchestrator file

from data_cleaning import run_data_cleaning
from python_sql_creation import connect, create_mysql_tables, insert_sample_data


def main():
    """
    Main pipeline function.
    Runs data cleaning, database table creation,
    and inserts entity instances with no user input.
    """

    # -----------------------------
    # Step 1: Data Cleaning + Merge
    # -----------------------------
    print("Running data cleaning pipeline...")
    run_data_cleaning(
        movies_path="movies.csv",
        tv_shows_path="tv_shows.csv",
        netflix_titles_path="netflix_titles.csv",
        output_path="cleaned_netflix_movies.csv"
    )

    # -----------------------------
    # Step 2: Connect to MySQL
    # -----------------------------
    print("Connecting to MySQL database...")
    engine = connect()

    # -----------------------------
    # Step 3: Drop & Create Tables
    # -----------------------------
    print("Creating database tables from scratch...")
    create_mysql_tables(engine)

    # -----------------------------
    # Step 4: Insert Entity Instances
    # -----------------------------
    print("Inserting entity instances...")
    insert_sample_data(engine, "cleaned_netflix_movies.csv")

    print("Pipeline executed successfully!")


# Ensures main() runs when file is executed directly
if __name__ == "__main__":
    main()