# -*- coding: utf-8 -*-
"""python_sql_query.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i_5jRr9Lvc57KUPoibpKi0D-2xbRPmgk
"""

import pandas as pd
import sqlite3

# Read the CSV
df = pd.read_csv("cleaned_netflix_movies (1).csv")

# Create an in-memory SQLite database
conn = sqlite3.connect(":memory:")

# Load DataFrame into SQL table
df.to_sql("netflix", conn, index=False, if_exists="replace")

print("✅ Data loaded into SQLite")

import pandas as pd

# Question 1
# What genres should Netflix consider adding to their platform?

df = pd.read_csv("cleaned_netflix_movies (1).csv")

genres = (
    df["genres"]
    .dropna()
    .str.split(",")
    .explode()
    .str.strip()
)

genre_counts = genres.value_counts().reset_index()
genre_counts.columns = ["genre", "count"]

print(genre_counts.head(10))
print(genre_counts.tail(10))

from sqlalchemy import create_engine

engine = create_engine("sqlite:///:memory:")
df.to_sql("netflix", engine, index=False, if_exists="replace")

sql_query = """
SELECT TRIM(value) AS genre, COUNT(*) AS count
FROM netflix,
     json_each('["' || REPLACE(genres, ',', '","') || '"]')
GROUP BY genre
ORDER BY count DESC;
"""

import pandas as pd

pd.read_sql_query(sql_query, engine)

from sqlalchemy import text

with engine.connect() as conn:
    conn.execute(text("""
        CREATE INDEX idx_genres
        ON netflix(genres);
    """))
pd.read_sql_query(sql_query, engine).head(10)

explain_query = """
EXPLAIN QUERY PLAN
SELECT TRIM(value) AS genre, COUNT(*) AS count
FROM netflix,
     json_each('["' || REPLACE(genres, ',', '","') || '"]')
GROUP BY genre
ORDER BY count DESC;
"""

pd.read_sql_query(explain_query, engine)

crime = df[df["genres"].str.contains("Crime", na=False)]

crime_per_country = (
    crime["country"]
    .value_counts()
    .reset_index()
)

crime_per_country.columns = ["country", "crime_count"]
print(crime_per_country.head(10))

sql_query = """
SELECT country, COUNT(*) AS crime_shows
FROM netflix
WHERE genres LIKE '%Crime%'
GROUP BY country
ORDER BY crime_shows DESC;
"""

pd.read_sql_query(sql_query, engine)

pd.read_sql_query("""
EXPLAIN QUERY PLAN
SELECT country, COUNT(*)
FROM netflix
WHERE genres LIKE '%Crime%'
GROUP BY country;
""", engine)

# Question 3
engagement = (
    df.groupby("type")
      .agg(
          avg_popularity=("popularity", "mean"),
          avg_vote_count=("vote_count", "mean"),
          avg_rating=("vote_average", "mean")
      )
      .reset_index()
)

print(engagement)

sql_query = """
SELECT
    type,
    AVG(popularity) AS avg_popularity,
    AVG(vote_count) AS avg_vote_count,
    AVG(vote_average) AS avg_rating
FROM netflix
GROUP BY type;
"""

pd.read_sql_query(sql_query, engine)

with engine.connect() as conn:
    conn.execute(text("""
        CREATE INDEX idx_type
        ON netflix(type);
    """))

pd.read_sql_query("""
EXPLAIN QUERY PLAN
SELECT
    type,
    AVG(popularity),
    AVG(vote_count),
    AVG(vote_average)
FROM netflix
GROUP BY type;
""", engine)

collab_df = df.dropna(subset=["director", "cast"])

collab_df = collab_df.assign(
    cast_member=collab_df["cast"].str.split(",")
).explode("cast_member")

collab_df["cast_member"] = collab_df["cast_member"].str.strip()

collaborations = (
    collab_df
    .groupby(["director", "cast_member"])
    .size()
    .reset_index(name="collaboration_count")
    .sort_values("collaboration_count", ascending=False)
)


print(collaborations.head(10))

sql_query = """
SELECT
    director,
    "cast",
    COUNT(*) AS collaboration_count
FROM netflix
WHERE director IS NOT NULL
  AND "cast" IS NOT NULL
GROUP BY director, "cast"
ORDER BY collaboration_count DESC
LIMIT 10;
"""

pd.read_sql_query(sql_query, engine)

from sqlalchemy import text

with engine.connect() as conn:
    conn.execute(text("""
        CREATE INDEX IF NOT EXISTS idx_director
        ON netflix(director);
    """))
    conn.execute(text("""
        CREATE INDEX IF NOT EXISTS idx_cast
        ON netflix("cast");
    """))

pd.read_sql_query("""
EXPLAIN QUERY PLAN
SELECT director, "cast", COUNT(*)
FROM netflix
WHERE director IS NOT NULL
  AND "cast" IS NOT NULL
GROUP BY director, "cast";
""", engine)